# Generated by Django 4.0 on 2021-12-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcheck', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodingredients',
            old_name='food_name',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='foodingredients',
            old_name='ingredients_name',
            new_name='ingredients',
        ),
    ]
