# Generated by Django 4.0 on 2021-12-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcheck', '0002_rename_food_name_foodingredients_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredients_count',
            field=models.IntegerField(default=0),
        ),
    ]
